[default]
date = "Date"
description = "Narration"
reference = "Chq./Ref.No."
value_date = "Value Dt"
withdrawal_amount = "Withdrawal Amt."
deposit_amount = "Deposit Amt."
closing_balance = "Closing Balance"
